authProject/urls.py
from django.contrib import admin
from django.urls import path, include
from shuyuadmin import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('login', views.login),
    path('shuyuadmin/', include('shuyuadmin.urls'))
]

shuyuadmin/urls.py
from django.urls import path
from shuyuadmin import views

urlpatterns = [
    path('', views.table_obj_index, name='index'),
    path('index', views.table_obj_index, name='index'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('register', views.register, name='register'),
    path('reset', views.password_reset, name='password_reset'),
    path('reminder', views.password_reminder, name='password_reminder'),
    path('test', views.test),

    path('<app_name>/<table_name>', views.table_obj_display, name='table_obj_display'),
    path('<app_name>/<table_name>/add', views.table_obj_add, name='table_obj_add'),
    path('<app_name>/<table_name>/delete/<int:nid>', views.table_obj_delete, name='table_obj_delete'),
    path('<app_name>/<table_name>/update/<int:nid>', views.table_obj_update, name='table_obj_update'),
    path('<app_name>/<table_name>/show/<int:nid>', views.table_obj_show, name='table_obj_show'),
]

shuyuadmin/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    nickname = models.CharField(max_length=32, null=True, blank=True)
    address = models.CharField(max_length=256, null=True, blank=True)
    roles = models.ManyToManyField(verbose_name='角色', to='Role')

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'

    class Meta:
        verbose_name_plural = '用户管理'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class Menu(models.Model):
    """
    菜单
    """
    title = models.CharField(max_length=32, unique=True)
    open = models.BooleanField(null=True, blank=True, default=True)
    sort_index = models.IntegerField(null=True, blank=True, default=1)
    parent = models.ForeignKey('Menu', null=True, blank=True, on_delete=models.CASCADE)
    icon = models.CharField(max_length=32, null=True, blank=True)

    # 定义菜单间的自引用关系
    # 权限url 在 菜单下；菜单可以有父级菜单；还要支持用户创建菜单，因此需要定义parent字段（parent_id）
    # blank=True 意味着在后台管理中填写可以为空，根菜单没有父级菜单

    class Meta:
        verbose_name_plural = '菜单管理'

    def __str__(self):
        title_list = [self.title]
        p = self.parent
        while p:
            title_list.insert(0, p.title)
            p = p.parent
        return '->'.join(title_list)


class Permission(models.Model):
    """
    权限
    """
    title = models.CharField(max_length=64, unique=True, verbose_name='名称')
    url = models.CharField(max_length=256)
    app_name = models.CharField(max_length=32, verbose_name='应用名')
    table_name = models.CharField(max_length=32, verbose_name='表名')
    open = models.BooleanField(null=True, blank=True, default=True)
    menu = models.ForeignKey('Menu', null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '权限管理'

    def __str__(self):
        return '%s-%s' % (self.menu, self.title)


class Role(models.Model):
    """
    角色
    """
    title = models.CharField(max_length=64, unique=True)
    permissions = models.ManyToManyField('Permission')

    class Meta:
        verbose_name_plural = '角色管理'

    def __str__(self):
        return self.title


class Product(models.Model):
    name = models.CharField(max_length=128, unique=True)
    type_choice1 = (
        (1, '16G'),
        (2, '32G'),
        (3, '4G'),
        (4, '8G'),
    )
    choice1 = models.SmallIntegerField(choices=type_choice1, verbose_name='内存容量')
    type_choice2 = (
        (1, '集成显卡'),
        (2, '独立显卡'),
    )
    choice2 = models.SmallIntegerField(choices=type_choice2, verbose_name='显卡类型')

    type_choice3 = (
        (1, 'Windows 10'),
        (2, 'Mac OS'),
        (3, 'Linux'),
    )
    choice3 = models.SmallIntegerField(choices=type_choice3, verbose_name='操作系统')

    size = models.CharField(max_length=10)
    comment = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "产品管理"


class Icons(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "图标管理"

shuyuadmin/views.py
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from shuyuadmin.admin_sites import site
from shuyuadmin.utils import pager, permissions
from shuyuadmin.utils.form_handle import create_model_form
from shuyuadmin.models import Icons
import json


@login_required()
def index(request):
    return_data = {
        'enabled_admins': site.enabled_admins,
        'my_menu': permissions.get_permissions_menu(request.user)
    }
    return render(request, 'shuyuadmin/table_obj_index.html', return_data)


def login(request):
    """
    登录
    :param request:
    :return:
    """
    return_data = {
        'errors': '',
        'username': ''
    }
    if request.method == 'GET':
        return render(request, 'shuyuadmin/login.html', return_data)
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        next_page = request.GET.get('next') or '/shuyuadmin/index'
        user = authenticate(request, email=username, password=password)
        if user:
            auth_login(request, user)
            return redirect(next_page)
        else:
            return_data['errors'] = '用户名或者密码错误'
            return_data['username'] = username
        return render(request, 'shuyuadmin/login.html', return_data)


@login_required
def logout(request):
    """
    注销
    :param request:
    :return:
    """
    return_data = {
        'errors': ''
    }
    auth_logout(request)
    return render(request, 'shuyuadmin/login.html', return_data)


@login_required
def password_reset(request):
    """
    密码重置
    :param request:
    :return:
    """
    pass


@login_required
def password_reminder(request):
    """
    忘记密码
    :param request:
    :return:
    """
    pass


def register(request):
    """
    注册
    :param request:
    :return:
    """
    pass


@login_required
def table_obj_index(request):
    return_data = {
        'enabled_admins': site.enabled_admins,
        'my_menu': permissions.get_permissions_menu(request.user),
    }
    return render(request, 'shuyuadmin/table_obj_index.html', return_data)


@login_required
def table_obj_display(request, app_name, table_name):
    # # 通过反射根据表名获取表名的对象
    # model_obj = getattr(models_module, table_name)
    # 不通过上面的反射获取model对象 直接通过app_name 和table_name 到king_admin字典里面获取
    admin_class = site.enabled_admins[app_name][table_name]
    object_list, filter_conditions = pager.table_filter(request, admin_class)
    admin_class.filter_conditions = filter_conditions

    # 分页
    # paginator = Paginator(object_list, admin_class.per_page)
    # print(paginator.page_range)
    # object_list = paginator.page(1)

    page_data = pager.split_page(object_list, page_num=request.GET.get('page'), per_page=admin_class.list_per_page)
    return_data = {
        'enabled_admins': site.enabled_admins,
        'app_name': app_name,
        'table_name': table_name,
        "page_data": page_data,
        'admin_class': admin_class,
        'my_menu': permissions.get_permissions_menu(request.user),
    }

    return render(request, 'shuyuadmin/%s_display.html' % admin_class.display_html_pre, return_data)


@login_required
def table_obj_add(request, app_name, table_name):
    admin_class = site.enabled_admins[app_name][table_name]
    dynamic_form = create_model_form(admin_class, add=True)
    my_menu = permissions.get_permissions_menu(request.user)
    icons = Icons.objects.all()
    errors_obj = {}
    errors = json.dumps(errors_obj)
    if request.method == 'GET':
        return render(request, 'shuyuadmin/table_obj_add.html', locals())
    elif request.method == 'POST':
        show_form = dynamic_form(request.POST)
        if show_form.is_valid():
            admin_class.model.objects.create(**show_form.cleaned_data)
            success = '操作成功'
        else:
            errors = show_form.errors.as_json()
        return render(request, 'shuyuadmin/table_obj_add.html', locals())


@login_required
def table_obj_show(request, app_name, table_name, nid):
    admin_class = site.enabled_admins[app_name][table_name]
    dynamic_form = create_model_form(admin_class, add=False, show=True)
    my_menu = permissions.get_permissions_menu(request.user)
    obj_id = nid
    try:
        obj = admin_class.model.objects.get(id=nid)
    except admin_class.model.DoesNotExist:
        return redirect('/shuyuadmin/%s/%s' % (app_name, table_name))
    show_form = dynamic_form(instance=obj)
    return render(request, 'shuyuadmin/table_obj_show.html', locals())


@login_required
def table_obj_delete(request, app_name, table_name, nid):
    admin_class = site.enabled_admins[app_name][table_name]
    admin_class.model.objects.filter(id=nid).delete()
    return redirect('/shuyuadmin/%s/%s' % (app_name, table_name))


@login_required
def table_obj_update(request, app_name, table_name, nid):
    admin_class = site.enabled_admins[app_name][table_name]
    dynamic_form = create_model_form(admin_class, add=False)
    my_menu = permissions.get_permissions_menu(request.user)
    obj_id = nid
    icons = Icons.objects.all()
    try:
        obj = admin_class.model.objects.get(id=nid)
    except admin_class.model.DoesNotExist:
        return redirect('/shuyuadmin/%s/%s' % (app_name, table_name))
    show_form = dynamic_form(instance=obj)

    errors_obj = {}
    errors = json.dumps(errors_obj)
    success = ''
    if request.method == 'GET':
        return render(request, 'shuyuadmin/table_obj_update.html', locals())
    elif request.method == 'POST':
        obj = admin_class.model.objects.get(id=nid)
        show_form = dynamic_form(request.POST, instance=obj)
        if show_form.is_valid():
            obj.save()
            success = '操作成功'
        else:
            errors = show_form.errors.as_json()
        return render(request, 'shuyuadmin/table_obj_update.html', locals())


def test(request):
    from shuyuadmin.models import Icons
    icons = Icons.objects.all()

    return render(request, 'test.html', locals())

templates/shuyuadmin/table_obj_add.html
{% extends 'shuyuadmin/table_obj_index.html' %}
{% load tags %}

{% block page-head %}
                <div id="page-head">
                        <div id="page-title">
                            <h1 class="page-header text-overflow">{% get_table_name2 app_name table_name %}</h1>
                        </div>
                        <!--Breadcrumb-->
                        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                        <ol class="breadcrumb">
                        <li><a href="/shuyuadmin/"><i class="demo-pli-home"></i></a></li>
                        <li><a href="/shuyuadmin/">首页</a></li>
                        <li><a href="/shuyuadmin/{{ app_name }}/{{ table_name }}">{% get_table_name2 app_name table_name %}</a></li>
                        <li><a href="/shuyuadmin/{{ app_name }}/{{ table_name }}/add">添加</a></li>
                        </ol>
                        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                        <!--End breadcrumb-->
                </div>
{% endblock %}


{% block head %}
    <!--Switchery [ OPTIONAL ]-->
    <link href="/statics/plugins/switchery/switchery.min.css" rel="stylesheet">


    <!--Bootstrap Select [ OPTIONAL ]-->
    <link href="/statics/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet">


    <!--Bootstrap Tags Input [ OPTIONAL ]-->
    <link href="/statics/plugins/bootstrap-tagsinput/bootstrap-tagsinput.min.css" rel="stylesheet">


    <!--Chosen [ OPTIONAL ]-->
    <link href="/statics/plugins/chosen/chosen.min.css" rel="stylesheet">


    <!--noUiSlider [ OPTIONAL ]-->
    <link href="/statics/plugins/noUiSlider/nouislider.min.css" rel="stylesheet">


    <!--Select2 [ OPTIONAL ]-->
    <link href="/statics/plugins/select2/css/select2.min.css" rel="stylesheet">


    <!--Bootstrap Timepicker [ OPTIONAL ]-->
    <link href="/statics/plugins/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet">


    <!--Bootstrap Datepicker [ OPTIONAL ]-->
    <link href="/statics/plugins/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet">
{% endblock %}

{% block page-content %}
    <!--Page content-->
    <!--===================================================-->
    <div id="page-content">
					    <div class="panel">
					        <div class="panel-body">
					            <div class="panel-heading">
					                <h3 class="panel-title">{% get_table_name2 app_name table_name %}-添加记录</h3>
					            </div>
                                <hr>
                                 <form class="panel-body form-horizontal form-padding" method="post">
                                 {% csrf_token %}
                                    {% for field in dynamic_form %}
                                        <div class="form-group">
                                            <label class="col-md-3 control-label" for="id_{{ field.name }}">{% get_cn_label admin_class field.label %}</label>
                                            <div class="col-md-9">
                                                {{ field }}
                                                <small class="text-pink">{% get_errors_message errors field.name %}</small>
                                            </div>
					                    </div>
                                    {% endfor %}
                                 <div class="col-md-1 pull-right">
                                     <input class="btn btn-primary" type="submit" value="保存">
                                 </div>
                                 </form>
					        </div>
					    </div>

                        <!--Default Bootstrap Modal-->
                        <!--===================================================-->
                        <div class="modal fade" id="demo-default-modal" role="dialog" tabindex="-1" aria-labelledby="demo-default-modal" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">

                                    <!--Modal header-->
                                    <div class="modal-header">
                                        <h4 class="modal-title">点击图标进行选择</h4>
                                    </div>

                                    <!--Modal body-->
                                    <div class="modal-body">

                                                                <div class="nano" style="height:360px">
                                                                    <div class="nano-content">
                                                                        <div class="clearfix demo-icon-list">
                                                                                 {% for icon in icons %}
                                                                                <div class="col-sm-1 col-md-2">
                                                                                    <div class="demo-icon" ><i id="id-demo-icon" data-dismiss="modal" class="{{ icon.name }}" onclick="choose_icons('{{ icon.name }}')"></i></div>
                                                                                </div>
                                                                                {% endfor %}
                                                                        </div>
                                                                    </div>
                                                                </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--===================================================-->
                        <!--End Default Bootstrap Modal-->



                </div>
    <!--===================================================-->
    <!--End page content-->
{% endblock %}

{% block menu %}
                                 <!--Category name-->
                                <ul id="mainnav-menu" class="list-group">
                                    {% for id, menu in my_menu.items %}
                                        {% if menu.status %}
                                            <li class="{% get_menu_active_class my_menu table_name id %}">
                                                <a href="#">
                                                    <i class="{{ menu.icon }}"></i>
                                                    <span class="menu-title">{{ menu.title }}</span>
                                                    <i class="arrow"></i>
                                                </a>


                                                <!--Submenu-->
                                                <ul class="collapse">
                                                    {% for children_menu in menu.children %}
                                                        {% for sub_id, sub_menu in children_menu.items %}
                                                            {% if  sub_menu.status %}
                                                                <li class="{% get_menu_url_active_class my_menu table_name sub_id %}"><a href="/shuyuadmin/{{ sub_menu.app_name }}/{{ sub_menu.table_name }}">{{ sub_menu.title }}</a></li>
                                                            {% endif %}
                                                        {% endfor %}
                                                    {% endfor %}
                                                </ul>
                                            </li>
                                        {% endif %}
                                    {% endfor %}

                                </ul>

{% endblock %}

{% block javascript %}

 <!--=================================================-->

    <!--Switchery [ OPTIONAL ]-->
    <script src="/statics/plugins/switchery/switchery.min.js"></script>


    <!--Bootstrap Select [ OPTIONAL ]-->
    <script src="/statics/plugins/bootstrap-select/bootstrap-select.min.js"></script>


    <!--Bootstrap Tags Input [ OPTIONAL ]-->
    <script src="/statics/plugins/bootstrap-tagsinput/bootstrap-tagsinput.min.js"></script>


    <!--Chosen [ OPTIONAL ]-->
    <script src="/statics/plugins/chosen/chosen.jquery.min.js"></script>


    <!--noUiSlider [ OPTIONAL ]-->
    <script src="/statics/plugins/noUiSlider/nouislider.min.js"></script>


    <!--Select2 [ OPTIONAL ]-->
    <script src="/statics/plugins/select2/js/select2.min.js"></script>


    <!--Bootstrap Timepicker [ OPTIONAL ]-->
    <script src="/statics/plugins/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>


    <!--Bootstrap Datepicker [ OPTIONAL ]-->
    <script src="/statics/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>


    <!--Form Component [ SAMPLE ]-->
    <script src="/statics/js/demo/form-component.js"></script>
    <!--Modals [ SAMPLE ]-->
    <script src="/statics/js/demo/ui-modals.js"></script>
            <script>
        $(document).ready(function () {
            $("#id_icon").on('click', function () {
                $('#demo-default-modal').css('display', "Block");
                $('#demo-default-modal').addClass('in');
                let div = $("<div class='modal-backdrop fade in' ></div>");
                $('body').append(div);
                $('body').addClass('modal-open');
            });
        });

        function f_submit() {
            if(confirm("请确认修改！")){
                return true;
            }
        };

        function choose_icons(icon_text) {
                $('#id_icon').attr('value', icon_text);
                $('#demo-default-modal').css('display', "none");
                $('#demo-default-modal').removeClass('in');
                $('div').remove('.modal-backdrop.fade.in');
                $('body').removeClass('modal-open');

            };
    </script>
{% endblock %}

templates/shuyuadmin/table_obj_update.html
{% extends 'shuyuadmin/table_obj_index.html' %}
{% load tags %}

{% block page-head %}
                <div id="page-head">
                        <div id="page-title">
                            <h1 class="page-header text-overflow">{% get_table_name2 app_name table_name %}</h1>
                        </div>
                        <!--Breadcrumb-->
                        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                        <ol class="breadcrumb">
                        <li><a href="/shuyuadmin/"><i class="demo-pli-home"></i></a></li>
                        <li><a href="/shuyuadmin/">首页</a></li>
                        <li><a href="/shuyuadmin/{{ app_name }}/{{ table_name }}">{% get_table_name2 app_name table_name %}</a></li>
                        <li><a href="/shuyuadmin/{{ app_name }}/{{ table_name }}/update/{{ obj_id }}">编辑</a></li>
                        </ol>
                        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                        <!--End breadcrumb-->
                </div>
{% endblock %}

{% block head %}

    <!--Bootstrap Select [ OPTIONAL ]-->
    <link href="/statics/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet">

{% endblock %}

{% block page-content %}
    <!--Page content-->
    <!--===================================================-->
    <div id="page-content">

					    <div class="panel">
					        <div class="panel-body">
					            <div class="panel-heading">
					                <h3 class="panel-title">{% get_table_name2 app_name table_name %}-编辑记录</h3>
					            </div>
                                <hr>
                                 <form class="panel-body form-horizontal form-padding" method="post">
                                 {% csrf_token %}
                                    {% for field in show_form %}
                                        <div class="form-group">
                                            <label class="col-md-3 control-label" for="id_{{ field.name }}">{% get_cn_label admin_class field.label %}</label>
                                            <div class="col-md-9">
                                                {{ field }}
                                                <small class="text-pink">{% get_errors_message errors field.name %}</small>
                                            </div>
					                    </div>
                                    {% endfor %}
                                 <div class="col-md-1 pull-right">

                                     <input class="btn btn-primary" type="submit" onclick="return f_submit()" value="保存">
                                 </div>
                                 </form>
					        </div>
					    </div>



            <!--Default Bootstrap Modal-->
            <!--===================================================-->
            <div class="modal fade" id="demo-default-modal" role="dialog" tabindex="-1" aria-labelledby="demo-default-modal" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <!--Modal header-->
                        <div class="modal-header">
                            <h4 class="modal-title">点击图标进行选择</h4>
                        </div>

                        <!--Modal body-->
                        <div class="modal-body">

                                                    <div class="nano" style="height:360px">
                                                        <div class="nano-content">
                                                            <div class="clearfix demo-icon-list">
                                                                     {% for icon in icons %}
                                                                    <div class="col-sm-1 col-md-2">
                                                                        <div class="demo-icon" ><i id="id-demo-icon" data-dismiss="modal" class="{{ icon.name }}" onclick="choose_icons('{{ icon.name }}')"></i></div>
                                                                    </div>
                                                                    {% endfor %}
                                                            </div>
                                                        </div>
                                                    </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--===================================================-->
            <!--End Default Bootstrap Modal-->



    </div>
    <!--===================================================-->
    <!--End page content-->

{% endblock %}

{% block menu %}
                                 <!--Category name-->
                                <ul id="mainnav-menu" class="list-group">
                                    {% for id, menu in my_menu.items %}
                                        {% if menu.status %}
                                            <li class="{% get_menu_active_class my_menu table_name id %}">
                                                <a href="#">
                                                    <i class="{{ menu.icon }}"></i>
                                                    <span class="menu-title">{{ menu.title }}</span>
                                                    <i class="arrow"></i>
                                                </a>


                                                <!--Submenu-->
                                                <ul class="collapse">
                                                    {% for children_menu in menu.children %}
                                                        {% for sub_id, sub_menu in children_menu.items %}
                                                            {% if  sub_menu.status %}
                                                                <li class="{% get_menu_url_active_class my_menu table_name sub_id %}"><a href="/shuyuadmin/{{ sub_menu.app_name }}/{{ sub_menu.table_name }}">{{ sub_menu.title }}</a></li>
                                                            {% endif %}
                                                        {% endfor %}
                                                    {% endfor %}
                                                </ul>
                                            </li>
                                        {% endif %}
                                    {% endfor %}

                                </ul>

{% endblock %}

{% block javascript %}


    <!--Bootstrap Select [ OPTIONAL ]-->
    <script src="/statics/plugins/bootstrap-select/bootstrap-select.min.js"></script>

    <!--Modals [ SAMPLE ]-->
    <script src="/statics/js/demo/ui-modals.js"></script>

    <!--Form Component [ SAMPLE ]-->
    <script src="/statics/js/demo/form-component.js"></script>
        <script>
        $(document).ready(function () {
            $("#id_icon").on('click', function () {
                $('#demo-default-modal').css('display', "Block");
                $('#demo-default-modal').addClass('in');
                let div = $("<div class='modal-backdrop fade in' ></div>");
                $('body').append(div);
                $('body').addClass('modal-open');
            });
        });

        function f_submit() {
            if(confirm("请确认修改！")){
                return true;
            }
        };

        function choose_icons(icon_text) {
                $('#id_icon').attr('value', icon_text);
                $('#demo-default-modal').css('display', "none");
                $('#demo-default-modal').removeClass('in');
                $('div').remove('.modal-backdrop.fade.in');
                $('body').removeClass('modal-open');

            };
    </script>

{% endblock %}